# Generated by Django 4.2.29 on 2026-04-25 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('budgets', '0005_budget_line_refactor'),
        ('vendors', '0011_remove_rejected_from_vendor_profile_revision_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('settled', 'Settled'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('payment_method', models.CharField(choices=[('petty_cash', 'Petty Cash'), ('reimbursement', 'Reimbursement')], max_length=20)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=255)),
                ('reference_number', models.CharField(blank=True, default='', max_length=255)),
                ('expense_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('source_note', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_expenses', to='budgets.budget')),
                ('budget_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_expenses', to='budgets.budgetline')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_expenses', to='budgets.budgetcategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_manual_expenses', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_expenses', to='core.organization')),
                ('scope_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_expenses', to='core.scopenode')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_expenses', to='budgets.budgetsubcategory')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_expenses', to='vendors.vendor')),
            ],
            options={
                'db_table': 'manual_expense_entries',
            },
        ),
        migrations.CreateModel(
            name='ManualExpenseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='manual_expense_attachments/')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='manual_expenses.manualexpenseentry')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_expense_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manual_expense_attachments',
            },
        ),
        migrations.AddIndex(
            model_name='manualexpenseentry',
            index=models.Index(fields=['org', 'status'], name='manual_expe_org_id_3e4d17_idx'),
        ),
        migrations.AddIndex(
            model_name='manualexpenseentry',
            index=models.Index(fields=['org', 'scope_node'], name='manual_expe_org_id_772d61_idx'),
        ),
        migrations.AddIndex(
            model_name='manualexpenseentry',
            index=models.Index(fields=['created_by'], name='manual_expe_created_7916e0_idx'),
        ),
        migrations.AddIndex(
            model_name='manualexpenseentry',
            index=models.Index(fields=['expense_date'], name='manual_expe_expense_7e9599_idx'),
        ),
        migrations.AddIndex(
            model_name='manualexpenseentry',
            index=models.Index(fields=['budget', 'category', 'subcategory'], name='manual_expe_budget__026872_idx'),
        ),
        migrations.AddIndex(
            model_name='manualexpenseattachment',
            index=models.Index(fields=['expense_entry'], name='manual_expe_expense_1e2f5a_idx'),
        ),
    ]
