# Generated by Django 5.0.6 on 2026-04-15 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('invoice', 'Invoice'), ('campaign', 'Campaign'), ('vendor', 'Vendor'), ('budget', 'Budget')], max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('override_parent', models.BooleanField(default=False, help_text="If True, this row's is_active is authoritative regardless of parent.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_activations', to='core.scopenode')),
            ],
            options={
                'db_table': 'module_activations',
                'indexes': [models.Index(fields=['scope_node', 'module'], name='module_acti_scope_n_0a7b6f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='moduleactivation',
            constraint=models.UniqueConstraint(fields=('module', 'scope_node'), name='unique_module_per_node'),
        ),
    ]
