# Generated by Django 4.2.29 on 2026-04-16 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0003_campaign_v1'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='campaign',
            new_name='campaigns_org_id_2c9a09_idx',
            old_name='campaigns_org_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='campaign',
            new_name='campaigns_scope_n_30bd68_idx',
            old_name='campaigns_scope_status_idx',
        ),
        migrations.RenameIndex(
            model_name='campaign',
            new_name='campaigns_categor_1a20f8_idx',
            old_name='campaigns_category_idx',
        ),
        migrations.RenameIndex(
            model_name='campaign',
            new_name='campaigns_budget__65f8f9_idx',
            old_name='campaigns_budget_idx',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
    ]
