# Generated by Django 4.2.29 on 2026-04-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_rename_campaigns_org_id_status_idx_campaigns_org_id_2c9a09_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_budget', 'Pending Budget'), ('budget_variance_pending', 'Budget Variance Pending'), ('pending_workflow', 'Pending Workflow'), ('in_review', 'In Review'), ('internally_approved', 'Internally Approved'), ('finance_pending', 'Finance Pending'), ('finance_approved', 'Finance Approved'), ('finance_rejected', 'Finance Rejected'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
    ]
