# Generated by Django 4.2.29 on 2026-04-16 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceActionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=10)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'finance_action_tokens',
            },
        ),
        migrations.CreateModel(
            name='FinanceHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(help_text='invoice | campaign | vendor | budget', max_length=20)),
                ('subject_type', models.CharField(help_text='e.g. vendor_submission, invoice, campaign', max_length=30)),
                ('subject_id', models.PositiveBigIntegerField(help_text='PK of the subject record')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to Finance'), ('finance_approved', 'Finance Approved'), ('finance_rejected', 'Finance Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=25)),
                ('export_file', models.CharField(blank=True, help_text='Path or reference to the generated export file', max_length=500)),
                ('finance_reference_id', models.CharField(blank=True, help_text='External reference assigned by finance (e.g. SAP vendor code, invoice number)', max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_handoffs', to='core.organization')),
                ('scope_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_handoffs', to='core.scopenode')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_handoffs_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_handoffs',
            },
        ),
        migrations.CreateModel(
            name='FinanceDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('reference_id', models.CharField(blank=True, help_text='Finance-assigned reference (e.g. SAP vendor code, PO number)', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_via_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='finance.financeactiontoken')),
                ('handoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='finance.financehandoff')),
            ],
            options={
                'db_table': 'finance_decisions',
                'ordering': ['-acted_at'],
            },
        ),
        migrations.AddField(
            model_name='financeactiontoken',
            name='handoff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_tokens', to='finance.financehandoff'),
        ),
        migrations.AddIndex(
            model_name='financehandoff',
            index=models.Index(fields=['module', 'subject_type', 'subject_id'], name='finance_han_module_0247c4_idx'),
        ),
        migrations.AddIndex(
            model_name='financehandoff',
            index=models.Index(fields=['status'], name='finance_han_status_a0a371_idx'),
        ),
        migrations.AddIndex(
            model_name='financehandoff',
            index=models.Index(fields=['org', 'scope_node'], name='finance_han_org_id_d826af_idx'),
        ),
        migrations.AddIndex(
            model_name='financehandoff',
            index=models.Index(fields=['finance_reference_id'], name='finance_han_finance_d4b123_idx'),
        ),
        migrations.AddIndex(
            model_name='financedecision',
            index=models.Index(fields=['handoff', 'decision'], name='finance_dec_handoff_7ddd96_idx'),
        ),
        migrations.AddIndex(
            model_name='financeactiontoken',
            index=models.Index(fields=['token'], name='finance_act_token_b244b6_idx'),
        ),
        migrations.AddIndex(
            model_name='financeactiontoken',
            index=models.Index(fields=['handoff', 'action_type'], name='finance_act_handoff_bb962d_idx'),
        ),
    ]
