# Generated by Django 5.0.6 on 2026-04-15 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='scope_node',
            field=models.ForeignKey(help_text='Entity or company this invoice belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.scopenode'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['scope_node', 'status'], name='invoices_scope_n_c3778b_idx'),
        ),
    ]
