# Generated by Django 4.2.29 on 2026-04-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('in_review', 'In Review'), ('internally_approved', 'Internally Approved'), ('finance_pending', 'Finance Pending'), ('finance_approved', 'Finance Approved'), ('finance_rejected', 'Finance Rejected'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='draft', max_length=20),
        ),
    ]
