# Generated by Django 4.2.29 on 2026-04-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_activation_and_user_binding'),
        ('invoices', '0003_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='po_number',
            field=models.CharField(blank=True, help_text='Purchase Order number — required if vendor has PO mandate', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Bound vendor (populated for portal-created invoices)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='vendors.vendor'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['vendor'], name='invoices_vendor__3069dc_idx'),
        ),
    ]
