# Generated by Django 4.2.29 on 2026-04-18 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_split_join'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0006_alter_invoicedocument_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='selected_workflow_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_invoices', to='workflow.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='selected_workflow_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_invoices', to='workflow.workflowtemplateversion'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='workflow_selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='workflow_selected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_selections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_workflow', 'Pending Workflow'), ('pending', 'Pending'), ('in_review', 'In Review'), ('internally_approved', 'Internally Approved'), ('finance_pending', 'Finance Pending'), ('finance_approved', 'Finance Approved'), ('finance_rejected', 'Finance Rejected'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='draft', max_length=20),
        ),
    ]
