# Generated by Django 4.2.29 on 2026-04-19 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_alter_budgetrule_options'),
        ('campaigns', '0005_alter_campaign_status'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0004_split_join'),
        ('invoices', '0007_add_pending_workflow_and_workflow_linkage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('branch_pending', 'Branch Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('correction_required', 'Correction Required'), ('cancelled', 'Cancelled')], default='draft', max_length=25)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('revision_number', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_allocations', to=settings.AUTH_USER_MODEL)),
                ('branch', models.OneToOneField(blank=True, help_text='Branch task created for this allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_allocation', to='workflow.workflowinstancebranch')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_allocations', to='budgets.budget')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_allocations', to='campaigns.campaign')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_allocations', to='budgets.budgetcategory')),
                ('entity', models.ForeignKey(help_text='The scope node (entity) this allocation is assigned to', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_allocations', to='core.scopenode')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='invoices.invoice')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_allocations', to=settings.AUTH_USER_MODEL)),
                ('selected_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_allocations', to=settings.AUTH_USER_MODEL)),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_allocations', to=settings.AUTH_USER_MODEL)),
                ('split_step', models.ForeignKey(help_text='The RUNTIME_SPLIT_ALLOCATION instance step that owns this allocation', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_allocations', to='workflow.workflowinstancestep')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_allocations', to='budgets.budgetsubcategory')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_allocations', to='workflow.workflowinstance')),
            ],
            options={
                'db_table': 'invoice_allocations',
            },
        ),
        migrations.CreateModel(
            name='InvoiceAllocationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(help_text='Full allocation field snapshot at this revision')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.TextField(blank=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='invoices.invoiceallocation')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoice_allocation_revisions',
                'ordering': ['revision_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoiceallocationrevision',
            constraint=models.UniqueConstraint(fields=('allocation', 'revision_number'), name='unique_revision_per_allocation'),
        ),
        migrations.AddIndex(
            model_name='invoiceallocation',
            index=models.Index(fields=['invoice', 'status'], name='invoice_all_invoice_2ced17_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceallocation',
            index=models.Index(fields=['workflow_instance'], name='invoice_all_workflo_d04e30_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceallocation',
            index=models.Index(fields=['entity', 'status'], name='invoice_all_entity__40d754_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceallocation',
            index=models.Index(fields=['budget', 'status'], name='invoice_all_budget__e192c7_idx'),
        ),
    ]
