# Generated by Django 4.2.29 on 2026-04-22 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_vendor_submission_route'),
        ('invoices', '0008_invoiceallocation_invoiceallocationrevision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinvoicesubmission',
            name='send_to_route',
            field=models.ForeignKey(blank=True, help_text='VendorSubmissionRoute chosen by vendor at submit time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_submissions', to='vendors.vendorsubmissionroute'),
        ),
    ]
