# Generated by Django 4.2.29 on 2026-04-25 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0009_vendor_invoice_submission_send_to_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('rtgs', 'RTGS'), ('neft', 'NEFT'), ('imps', 'IMPS'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('other', 'Other')], default='', max_length=20)),
                ('payment_reference_number', models.CharField(blank=True, default='', max_length=255)),
                ('utr_number', models.CharField(blank=True, default='', max_length=255)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=255)),
                ('bank_reference_number', models.CharField(blank=True, default='', max_length=255)),
                ('payer_bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('beneficiary_name', models.CharField(blank=True, default='', max_length=255)),
                ('beneficiary_bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_record', to='invoices.invoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_invoice_payments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_invoice_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoice_payments',
                'indexes': [models.Index(fields=['invoice'], name='invoice_pay_invoice_b58bb5_idx'), models.Index(fields=['payment_status'], name='invoice_pay_payment_f9b2ec_idx'), models.Index(fields=['recorded_by'], name='invoice_pay_recorde_07417a_idx')],
            },
        ),
    ]
