# Generated by Django 4.2.29 on 2026-04-26 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0010_invoice_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinvoicesubmission',
            name='correction_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorinvoicesubmission',
            name='correction_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorinvoicesubmission',
            name='correction_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_submission_corrections_requested', to=settings.AUTH_USER_MODEL),
        ),
    ]
