# Generated by Django 5.0.6 on 2026-06-27 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_alter_permission_action'),
        ('budgets', '0008_budget_revisions'),
        ('campaigns', '0005_alter_campaign_status'),
        ('core', '0001_initial'),
        ('invoices', '0012_vendorinvoicesubmission_original_normalized_data'),
        ('workflow', '0008_stepkind_single_allocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='entry_source',
            field=models.CharField(choices=[('standard', 'Standard'), ('historical_import', 'Historical Import')], db_index=True, default='standard', max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='finance_reference_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='historical_import_key',
            field=models.CharField(blank=True, help_text='Deterministic duplicate-protection key for historical imports.', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='historical_posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='historical_posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historically_posted_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='historical_posting_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='historical_reversal_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='historical_reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='historical_reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historically_reversed_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceallocation',
            name='allocation_source',
            field=models.CharField(choices=[('workflow', 'Workflow'), ('historical_import', 'Historical Import')], db_index=True, default='workflow', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_workflow', 'Pending Workflow'), ('pending', 'Pending'), ('in_review', 'In Review'), ('internally_approved', 'Internally Approved'), ('finance_pending', 'Finance Pending'), ('finance_approved', 'Finance Approved'), ('finance_rejected', 'Finance Rejected'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('historical_posted', 'Historical Posted'), ('historical_reversed', 'Historical Reversed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceallocation',
            name='split_step',
            field=models.ForeignKey(blank=True, help_text='The RUNTIME_SPLIT_ALLOCATION instance step that owns this allocation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_allocations', to='workflow.workflowinstancestep'),
        ),
        migrations.AlterField(
            model_name='invoiceallocation',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_allocations', to='workflow.workflowinstance'),
        ),
        migrations.AlterField(
            model_name='invoicedocument',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='invoices.vendorinvoicesubmission'),
        ),
        migrations.AddConstraint(
            model_name='invoiceallocation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('allocation_source', 'workflow'), ('split_step__isnull', False), ('workflow_instance__isnull', False)), models.Q(('allocation_source', 'historical_import'), ('split_step__isnull', True), ('workflow_instance__isnull', True)), _connector='OR'), name='invoice_allocation_source_context'),
        ),
    ]
