# Generated by Django 5.0.6 on 2026-04-15 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Stable slug used in materialized paths', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='ScopeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Stable slug, unique among siblings', max_length=100)),
                ('node_type', models.CharField(choices=[('company', 'Company'), ('entity', 'Entity'), ('region', 'Region'), ('branch', 'Branch'), ('department', 'Department'), ('cost_center', 'Cost Center')], max_length=50)),
                ('path', models.CharField(help_text='Materialized path e.g. /org_code/company_code/entity_code', max_length=2000)),
                ('depth', models.PositiveIntegerField(default=0, help_text='0 = direct child of org')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_nodes', to='core.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.scopenode')),
            ],
            options={
                'db_table': 'scope_nodes',
                'indexes': [models.Index(fields=['path'], name='scope_nodes_path_60fbca_idx'), models.Index(fields=['org', 'node_type'], name='scope_nodes_org_id_7268e5_idx'), models.Index(fields=['org', 'is_active'], name='scope_nodes_org_id_61c7bf_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='scopenode',
            constraint=models.UniqueConstraint(fields=('org', 'parent', 'code'), name='unique_sibling_code'),
        ),
    ]
