# Generated by Django 5.0.6 on 2026-04-15 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StepGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField()),
                ('parallel_mode', models.CharField(choices=[('SINGLE', 'Single'), ('ALL_MUST_APPROVE', 'All Must Approve'), ('ANY_ONE_APPROVES', 'Any One Approves')], default='SINGLE', max_length=30)),
                ('on_rejection_action', models.CharField(choices=[('TERMINATE', 'Terminate'), ('GO_TO_GROUP', 'Go To Group')], default='TERMINATE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('on_rejection_goto_group', models.ForeignKey(blank=True, help_text='Target group on rejection if action=GO_TO_GROUP. References stable group id.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejection_sources', to='workflow.stepgroup')),
            ],
            options={
                'db_table': 'step_groups',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(help_text='e.g. invoice, campaign, vendor, budget', max_length=50)),
                ('subject_id', models.PositiveBigIntegerField(help_text='PK of the subject record')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FROZEN', 'Frozen'), ('STUCK', 'Stuck')], default='DRAFT', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_workflow_instances', to=settings.AUTH_USER_MODEL)),
                ('subject_scope_node', models.ForeignKey(help_text='Denormalized from subject for fast scope checks', on_delete=django.db.models.deletion.PROTECT, related_name='workflow_instances', to='core.scopenode')),
            ],
            options={
                'db_table': 'workflow_instances',
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstanceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESET', 'Reset')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_groups', to='workflow.workflowinstance')),
                ('step_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instance_groups', to='workflow.stepgroup')),
            ],
            options={
                'db_table': 'workflow_instance_groups',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='current_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowinstancegroup'),
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scope_resolution_policy', models.CharField(choices=[('SUBJECT_NODE', 'Subject Node'), ('ANCESTOR_OF_TYPE', 'Ancestor Of Type'), ('ORG_ROOT', 'Org Root'), ('FIXED_NODE', 'Fixed Node')], max_length=30)),
                ('ancestor_node_type', models.CharField(blank=True, help_text='Used only when policy=ANCESTOR_OF_TYPE', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_user', models.ForeignKey(blank=True, help_text='Optional convenience — validated at instance creation, not authority source', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_workflow_steps', to=settings.AUTH_USER_MODEL)),
                ('fixed_scope_node', models.ForeignKey(blank=True, help_text='Used only when policy=FIXED_NODE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_workflow_steps', to='core.scopenode')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.stepgroup')),
                ('required_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_steps', to='access.role')),
            ],
            options={
                'db_table': 'workflow_steps',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstanceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped'), ('ORPHANED', 'Orphaned'), ('REASSIGNED', 'Reassigned')], default='WAITING', max_length=20)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('reassigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflow_steps', to=settings.AUTH_USER_MODEL)),
                ('instance_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_steps', to='workflow.workflowinstancegroup')),
                ('reassigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_by_steps', to=settings.AUTH_USER_MODEL)),
                ('reassigned_from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_from_steps', to=settings.AUTH_USER_MODEL)),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instance_steps', to='workflow.workflowstep')),
            ],
            options={
                'db_table': 'workflow_instance_steps',
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('module', models.CharField(help_text='e.g. invoice, campaign, vendor, budget', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_templates', to=settings.AUTH_USER_MODEL)),
                ('scope_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='core.scopenode')),
            ],
            options={
                'db_table': 'workflow_templates',
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='WorkflowTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_template_versions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workflow.workflowtemplate')),
            ],
            options={
                'db_table': 'workflow_template_versions',
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='template_version',
            field=models.ForeignKey(help_text='Locked at creation. Never changes.', on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow.workflowtemplateversion'),
        ),
        migrations.AddField(
            model_name='stepgroup',
            name='template_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_groups', to='workflow.workflowtemplateversion'),
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('STEP_ASSIGNED', 'Step Assigned'), ('STEP_APPROVED', 'Step Approved'), ('STEP_REJECTED', 'Step Rejected'), ('STEP_ORPHANED', 'Step Orphaned'), ('STEP_REASSIGNED', 'Step Reassigned'), ('INSTANCE_STUCK', 'Instance Stuck'), ('INSTANCE_FROZEN', 'Instance Frozen'), ('INSTANCE_APPROVED', 'Instance Approved'), ('INSTANCE_REJECTED', 'Instance Rejected')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_workflow_events', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_workflow_events', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workflow.workflowinstance')),
            ],
            options={
                'db_table': 'workflow_events',
                'indexes': [models.Index(fields=['instance', 'event_type'], name='workflow_ev_instanc_756584_idx'), models.Index(fields=['instance', 'created_at'], name='workflow_ev_instanc_2e81c1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowinstancestep',
            constraint=models.UniqueConstraint(fields=('instance_group', 'workflow_step'), name='unique_step_per_instance_group'),
        ),
        migrations.AddConstraint(
            model_name='workflowtemplate',
            constraint=models.UniqueConstraint(fields=('module', 'scope_node'), name='unique_template_per_module_per_node'),
        ),
        migrations.AddIndex(
            model_name='workflowtemplateversion',
            index=models.Index(fields=['template', 'status'], name='workflow_te_templat_f93b0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowtemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version_number'), name='unique_version_per_template'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['subject_type', 'subject_id'], name='workflow_in_subject_b90914_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['subject_scope_node', 'status'], name='workflow_in_subject_1b87d3_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['status'], name='workflow_in_status_a4291a_idx'),
        ),
        migrations.AddConstraint(
            model_name='stepgroup',
            constraint=models.UniqueConstraint(fields=('template_version', 'display_order'), name='unique_group_order_per_version'),
        ),
    ]
