# Generated by Django 5.0.6 on 2026-04-15 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowinstance',
            name='template',
        ),
        migrations.AddConstraint(
            model_name='workflowtemplateversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('template',), name='unique_published_version_per_template'),
        ),
    ]
