# Generated by Django 4.2.29 on 2026-04-17 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0003_workflowinstancestep_assignment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='join_policy',
            field=models.CharField(blank=True, choices=[('ALL_BRANCHES_MUST_COMPLETE', 'All Branches Must Complete')], default='', help_text='Used when step_kind=JOIN_BRANCHES to determine when join completes', max_length=30),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='split_target_mode',
            field=models.CharField(blank=True, default='', help_text='EXPLICIT_NODES = use split_target_nodes list; CHILD_NODES = use direct children of subject node', max_length=30),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='split_target_nodes',
            field=models.JSONField(blank=True, default=list, help_text='Used when step_kind=SPLIT_BY_SCOPE. List of scope_node IDs that will each receive one branch. Snapshotted at split activation time — not a live reference.'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='step_kind',
            field=models.CharField(choices=[('NORMAL_APPROVAL', 'Normal Approval'), ('SPLIT_BY_SCOPE', 'Split By Scope'), ('JOIN_BRANCHES', 'Join Branches')], default='NORMAL_APPROVAL', help_text='Controls whether this step is a normal approval or a split/join step', max_length=30),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='event_type',
            field=models.CharField(choices=[('STEP_ASSIGNED', 'Step Assigned'), ('STEP_APPROVED', 'Step Approved'), ('STEP_REJECTED', 'Step Rejected'), ('STEP_ORPHANED', 'Step Orphaned'), ('STEP_REASSIGNED', 'Step Reassigned'), ('INSTANCE_STUCK', 'Instance Stuck'), ('INSTANCE_FROZEN', 'Instance Frozen'), ('INSTANCE_APPROVED', 'Instance Approved'), ('INSTANCE_REJECTED', 'Instance Rejected'), ('BRANCH_ASSIGNED', 'Branch Assigned'), ('BRANCH_APPROVED', 'Branch Approved'), ('BRANCH_REJECTED', 'Branch Rejected'), ('BRANCH_REASSIGNED', 'Branch Reassigned'), ('BRANCHES_SPLIT', 'Branches Split'), ('BRANCHES_JOINED', 'Branches Joined')], max_length=30),
        ),
        migrations.AlterField(
            model_name='workflowinstancestep',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped'), ('ORPHANED', 'Orphaned'), ('REASSIGNED', 'Reassigned'), ('WAITING_BRANCHES', 'Waiting Branches')], default='WAITING', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkflowInstanceBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_index', models.PositiveIntegerField(default=0, help_text='Order of this branch among siblings (for display)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('assignment_state', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ASSIGNMENT_REQUIRED', 'Assignment Required'), ('NO_ELIGIBLE_USERS', 'No Eligible Users')], default='ASSIGNMENT_REQUIRED', max_length=30)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reassigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflow_branches', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(help_text='Back-reference to parent instance for fast querying', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='workflow.workflowinstance')),
                ('parent_instance_step', models.ForeignKey(help_text='The SPLIT_BY_SCOPE step that created this branch', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='workflow.workflowinstancestep')),
                ('reassigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_by_branches', to=settings.AUTH_USER_MODEL)),
                ('reassigned_from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_from_branches', to=settings.AUTH_USER_MODEL)),
                ('target_scope_node', models.ForeignKey(help_text='Frozen at split activation — the unit responsible for this branch', on_delete=django.db.models.deletion.PROTECT, related_name='workflow_branches', to='core.scopenode')),
            ],
            options={
                'db_table': 'workflow_instance_branches',
                'ordering': ['branch_index'],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowinstancebranch',
            constraint=models.UniqueConstraint(fields=('parent_instance_step', 'target_scope_node'), name='unique_branch_per_step_per_node'),
        ),
    ]
