# Generated by Django 4.2.29 on 2026-04-19 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_alter_budgetrule_options'),
        ('campaigns', '0005_alter_campaign_status'),
        ('core', '0001_initial'),
        ('access', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0004_split_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='allocation_total_policy',
            field=models.CharField(choices=[('MUST_EQUAL_INVOICE_TOTAL', 'Must Equal Invoice Total'), ('CAN_BE_PARTIAL', 'Can Be Partial')], default='MUST_EQUAL_INVOICE_TOTAL', help_text='Validation rule for total allocated amount vs invoice amount', max_length=30),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='allow_multiple_lines_per_entity',
            field=models.BooleanField(default=False, help_text='Allow more than one allocation row for the same entity'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='approver_selection_mode',
            field=models.CharField(choices=[('ROLE_RESOLVED', 'Role Resolved'), ('EXPLICIT_USER', 'Explicit User'), ('APPROVER_POOL', 'Approver Pool'), ('RUNTIME_SELECTED_FROM_POOL', 'Runtime Selected From Pool')], default='RUNTIME_SELECTED_FROM_POOL', help_text='How branch approvers are selected at split time', max_length=30),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='require_budget',
            field=models.BooleanField(default=False, help_text='Allocation must be linked to a budget'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='require_campaign',
            field=models.BooleanField(default=False, help_text='Allocation must be linked to a campaign'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='require_category',
            field=models.BooleanField(default=False, help_text='Allocation must have a budget category'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='require_subcategory',
            field=models.BooleanField(default=False, help_text='Allocation must have a budget subcategory'),
        ),
        migrations.AlterField(
            model_name='stepgroup',
            name='on_rejection_action',
            field=models.CharField(choices=[('TERMINATE', 'Terminate'), ('GO_TO_GROUP', 'Go To Group'), ('PREVIOUS_STAGE', 'Previous Stage'), ('RETURN_TO_SPLITTER', 'Return To Splitter'), ('RETURN_TO_SUBMITTER', 'Return To Submitter'), ('BRANCH_CORRECTION', 'Branch Correction')], default='TERMINATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='event_type',
            field=models.CharField(choices=[('STEP_ASSIGNED', 'Step Assigned'), ('STEP_APPROVED', 'Step Approved'), ('STEP_REJECTED', 'Step Rejected'), ('STEP_ORPHANED', 'Step Orphaned'), ('STEP_REASSIGNED', 'Step Reassigned'), ('INSTANCE_STUCK', 'Instance Stuck'), ('INSTANCE_FROZEN', 'Instance Frozen'), ('INSTANCE_APPROVED', 'Instance Approved'), ('INSTANCE_REJECTED', 'Instance Rejected'), ('BRANCH_ASSIGNED', 'Branch Assigned'), ('BRANCH_APPROVED', 'Branch Approved'), ('BRANCH_REJECTED', 'Branch Rejected'), ('BRANCH_REASSIGNED', 'Branch Reassigned'), ('BRANCHES_SPLIT', 'Branches Split'), ('BRANCHES_JOINED', 'Branches Joined'), ('SPLIT_ALLOCATIONS_SUBMITTED', 'Split Allocations Submitted'), ('SPLIT_ALLOCATION_CORRECTED', 'Split Allocation Corrected'), ('ALLOCATION_BUDGET_RESERVED', 'Allocation Budget Reserved'), ('ALLOCATION_BUDGET_RELEASED', 'Allocation Budget Released'), ('ALLOCATION_BUDGET_CONSUMED', 'Allocation Budget Consumed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='step_kind',
            field=models.CharField(choices=[('NORMAL_APPROVAL', 'Normal Approval'), ('SPLIT_BY_SCOPE', 'Split By Scope'), ('JOIN_BRANCHES', 'Join Branches'), ('RUNTIME_SPLIT_ALLOCATION', 'Runtime Split Allocation')], default='NORMAL_APPROVAL', help_text='Controls whether this step is a normal approval or a split/join step', max_length=30),
        ),
        migrations.CreateModel(
            name='WorkflowSplitOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_approvers', models.ManyToManyField(blank=True, help_text='Explicit approver pool; overrides role if both are set', related_name='allowed_split_options', to=settings.AUTH_USER_MODEL)),
                ('approver_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_options', to='access.role')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_options', to='budgets.budget')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_options', to='campaigns.campaign')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_options', to='budgets.budgetcategory')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_options', to='core.scopenode')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_options', to='budgets.budgetsubcategory')),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_options', to='workflow.workflowstep')),
            ],
            options={
                'db_table': 'workflow_split_options',
                'ordering': ['display_order'],
                'indexes': [models.Index(fields=['workflow_step', 'is_active'], name='workflow_sp_workflo_89cad5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowsplitoption',
            constraint=models.UniqueConstraint(fields=('workflow_step', 'entity'), name='unique_split_option_per_step_per_entity'),
        ),
    ]
