# Generated by Django 4.2.29 on 2026-04-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_workflowtemplate_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='branch_approval_policy',
            field=models.CharField(choices=[('REQUIRED_FOR_ALL', 'Required For All'), ('OPTIONAL_WHEN_CONFIGURED', 'Optional When Configured'), ('SKIP_ALL', 'Skip All')], default='REQUIRED_FOR_ALL', help_text='Controls whether branches from this split step require explicit approval. Only applies when step_kind=RUNTIME_SPLIT_ALLOCATION.', max_length=30),
        ),
    ]
