# Generated by Django 5.0.6 on 2026-04-15 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='scope_node',
            field=models.ForeignKey(help_text='Company or entity this budget is allocated to', on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='core.scopenode'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['scope_node', 'status'], name='budgets_scope_n_cb6330_idx'),
        ),
    ]
