# Generated by Django 4.2.29 on 2026-04-16 10:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('budgets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'budget_categories',
            },
        ),
        migrations.CreateModel(
            name='BudgetConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('campaign', 'Campaign'), ('invoice', 'Invoice'), ('manual_adjustment', 'Manual Adjustment')], max_length=20)),
                ('source_id', models.CharField(help_text='ID of the source record (campaign, invoice, etc.)', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('consumption_type', models.CharField(choices=[('reserved', 'Reserved'), ('consumed', 'Consumed'), ('released', 'Released'), ('adjusted', 'Adjusted')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('reversed', 'Reversed')], default='applied', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'budget_consumptions',
            },
        ),
        migrations.CreateModel(
            name='BudgetRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_threshold_percent', models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('approval_threshold_percent', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('hard_block_threshold_percent', models.DecimalField(decimal_places=2, default=Decimal('110.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('allowed_variance_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('require_hod_approval_on_variance', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'budget_rules',
            },
        ),
        migrations.CreateModel(
            name='BudgetSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'budget_subcategories',
            },
        ),
        migrations.CreateModel(
            name='BudgetVarianceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('campaign', 'Campaign'), ('invoice', 'Invoice'), ('manual_adjustment', 'Manual Adjustment')], max_length=20)),
                ('source_id', models.CharField(max_length=100)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_utilization_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('projected_utilization_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'budget_variance_requests',
            },
        ),
        migrations.RemoveField(
            model_name='budget',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='fiscal_year',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='title',
        ),
        migrations.AddField(
            model_name='budget',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='budget',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='consumed_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='budget',
            name='financial_year',
            field=models.CharField(blank=True, help_text='e.g. 2026-27', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.organization'),
        ),
        migrations.AddField(
            model_name='budget',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='period_type',
            field=models.CharField(blank=True, choices=[('yearly', 'Yearly'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('campaign', 'Campaign')], default='yearly', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='reserved_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='budget',
            name='scope_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='core.scopenode'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('exhausted', 'Exhausted'), ('frozen', 'Frozen'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['org', 'status'], name='budgets_org_id_8bd5b8_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['financial_year'], name='budgets_financi_960925_idx'),
        ),
        migrations.AddField(
            model_name='budgetvariancerequest',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variance_requests', to='budgets.budget'),
        ),
        migrations.AddField(
            model_name='budgetvariancerequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_variance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetvariancerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_variance_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='budgets.budgetcategory'),
        ),
        migrations.AddField(
            model_name='budgetrule',
            name='budget',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='budgets.budget'),
        ),
        migrations.AddField(
            model_name='budgetconsumption',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='budgets.budget'),
        ),
        migrations.AddField(
            model_name='budgetconsumption',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_consumptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to='core.organization'),
        ),
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='budgets.budgetcategory'),
        ),
        migrations.AddField(
            model_name='budget',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='budgets.budgetsubcategory'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['category', 'status'], name='budgets_categor_ef1a4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('scope_node', 'category', 'subcategory', 'financial_year', 'period_type', 'period_start', 'period_end'), name='unique_budget_allocation'),
        ),
        migrations.AddIndex(
            model_name='budgetvariancerequest',
            index=models.Index(fields=['budget', 'status'], name='budget_vari_budget__256892_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetvariancerequest',
            index=models.Index(fields=['source_type', 'source_id', 'status'], name='budget_vari_source__cc33ea_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetsubcategory',
            index=models.Index(fields=['category', 'is_active'], name='budget_subc_categor_5ab4c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetsubcategory',
            constraint=models.UniqueConstraint(fields=('category', 'code'), name='unique_subcategory_per_category'),
        ),
        migrations.AddIndex(
            model_name='budgetconsumption',
            index=models.Index(fields=['budget', 'source_type', 'source_id'], name='budget_cons_budget__2f939c_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetconsumption',
            index=models.Index(fields=['source_type', 'source_id'], name='budget_cons_source__3e241b_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetcategory',
            index=models.Index(fields=['org', 'is_active'], name='budget_cate_org_id_449ea3_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetcategory',
            constraint=models.UniqueConstraint(fields=('org', 'code'), name='unique_category_per_org'),
        ),
    ]
