# Generated by Django 4.2.29 on 2026-04-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_budgetcategory_budgetconsumption_budgetrule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetrule',
            options={'ordering': ['id']},
        ),
    ]
