# Generated by Django 4.2.29 on 2026-04-27 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0005_budget_line_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('financial_year', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('committed', 'Committed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('committed_rows', models.PositiveIntegerField(default=0)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committed_budget_import_batches', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budget_import_batches', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_import_batches', to='core.organization')),
            ],
            options={
                'db_table': 'budget_import_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='budgetconsumption',
            name='source_type',
            field=models.CharField(choices=[('campaign', 'Campaign'), ('invoice', 'Invoice'), ('invoice_allocation', 'Invoice Allocation'), ('manual_expense', 'Manual Expense'), ('manual_adjustment', 'Manual Adjustment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='budgetvariancerequest',
            name='source_type',
            field=models.CharField(choices=[('campaign', 'Campaign'), ('invoice', 'Invoice'), ('invoice_allocation', 'Invoice Allocation'), ('manual_expense', 'Manual Expense'), ('manual_adjustment', 'Manual Adjustment')], max_length=20),
        ),
        migrations.CreateModel(
            name='BudgetImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('error', 'Error'), ('committed', 'Committed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('raw_scope_node_code', models.CharField(blank=True, max_length=200)),
                ('raw_budget_code', models.CharField(blank=True, max_length=200)),
                ('raw_budget_name', models.CharField(blank=True, max_length=500)),
                ('raw_financial_year', models.CharField(blank=True, max_length=50)),
                ('raw_period_type', models.CharField(blank=True, max_length=50)),
                ('raw_period_start', models.CharField(blank=True, max_length=50)),
                ('raw_period_end', models.CharField(blank=True, max_length=50)),
                ('raw_category_code', models.CharField(blank=True, max_length=200)),
                ('raw_subcategory_code', models.CharField(blank=True, max_length=200)),
                ('raw_allocated_amount', models.CharField(blank=True, max_length=50)),
                ('raw_currency', models.CharField(blank=True, max_length=20)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='budgets.budgetimportbatch')),
                ('resolved_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='budgets.budget')),
                ('resolved_budget_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='budgets.budgetline')),
                ('resolved_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_import_rows', to='budgets.budgetcategory')),
                ('resolved_scope_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_import_rows', to='core.scopenode')),
                ('resolved_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_import_rows', to='budgets.budgetsubcategory')),
            ],
            options={
                'db_table': 'budget_import_rows',
                'ordering': ['row_number'],
                'indexes': [models.Index(fields=['batch', 'status'], name='budget_impo_batch_i_b02f44_idx'), models.Index(fields=['batch', 'row_number'], name='budget_impo_batch_i_4c77e6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='budgetimportbatch',
            index=models.Index(fields=['org', 'status'], name='budget_impo_org_id_62c65c_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetimportbatch',
            index=models.Index(fields=['created_by'], name='budget_impo_created_09dbd4_idx'),
        ),
    ]
