# Generated by Django 4.2.29 on 2026-04-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_budget_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetimportbatch',
            name='import_mode',
            field=models.CharField(choices=[('setup_only', 'Setup Only (Create Only)'), ('safe_update', 'Safe Update (Skip In-Use)'), ('full', 'Full Update')], default='safe_update', max_length=20),
        ),
        migrations.AddField(
            model_name='budgetimportbatch',
            name='skipped_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budgetimportrow',
            name='skipped_reason',
            field=models.TextField(blank=True),
        ),
    ]
