# Generated by Django 5.0.6 on 2026-06-19 09:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_budget_import_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('manual', 'Manual Edit'), ('excel', 'Excel Upload')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('published', 'Published'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('change_reason', models.TextField()),
                ('source_file', models.FileField(blank=True, null=True, upload_to='budget_revisions/source_files/')),
                ('source_file_name', models.CharField(blank=True, max_length=500)),
                ('base_budget_updated_at', models.DateTimeField(help_text='Optimistic concurrency marker captured when the revision was created.')),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='budgets.budget')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budget_revisions', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_budget_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'budget_revisions',
                'ordering': ['-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='BudgetRevisionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_key', models.CharField(max_length=100)),
                ('previous_allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('proposed_allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('change_type', models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('removed', 'Removed'), ('unchanged', 'Unchanged')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_lines', to='budgets.budgetline')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_revision_lines', to='budgets.budgetcategory')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budgets.budgetrevision')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_revision_lines', to='budgets.budgetsubcategory')),
            ],
            options={
                'db_table': 'budget_revision_lines',
                'ordering': ['category_id', 'subcategory_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='budgetrevision',
            index=models.Index(fields=['budget', 'status'], name='budget_revi_budget__2d4ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetrevision',
            index=models.Index(fields=['created_by'], name='budget_revi_created_13988f_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetrevision',
            constraint=models.UniqueConstraint(fields=('budget', 'revision_number'), name='unique_budget_revision_number'),
        ),
        migrations.AddIndex(
            model_name='budgetrevisionline',
            index=models.Index(fields=['revision', 'change_type'], name='budget_revi_revisio_6202c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetrevisionline',
            constraint=models.UniqueConstraint(fields=('revision', 'line_key'), name='unique_budget_revision_line_key'),
        ),
    ]
