# Generated by Django 4.2.29 on 2026-04-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('vendors', '0002_vendor_v1_overhaul'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendors_org_id_0616db_idx',
            old_name='vendors_org_opstatus_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendors_scope_n_f3adda_idx',
            old_name='vendors_scope_opstatus_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendors_sap_ven_29de4d_idx',
            old_name='vendors_sap_id_idx',
        ),
        migrations.RenameIndex(
            model_name='vendorfinanceactiontoken',
            new_name='vendor_fina_token_e237ec_idx',
            old_name='vendor_fat_token_idx',
        ),
        migrations.RenameIndex(
            model_name='vendorfinanceactiontoken',
            new_name='vendor_fina_submiss_939ef8_idx',
            old_name='vendor_fat_sub_action_idx',
        ),
        migrations.RenameIndex(
            model_name='vendorinvitation',
            new_name='vendor_invi_token_be9a5c_idx',
            old_name='vendor_inv_token_idx',
        ),
        migrations.RenameIndex(
            model_name='vendorinvitation',
            new_name='vendor_invi_org_id_fa66d3_idx',
            old_name='vendor_inv_org_status_idx',
        ),
        migrations.RenameIndex(
            model_name='vendorinvitation',
            new_name='vendor_invi_vendor__f2f118_idx',
            old_name='vendor_inv_email_idx',
        ),
        migrations.RenameIndex(
            model_name='vendoronboardingsubmission',
            new_name='vendor_onbo_invitat_2d8ab4_idx',
            old_name='vendor_sub_inv_status_idx',
        ),
        migrations.RenameIndex(
            model_name='vendoronboardingsubmission',
            new_name='vendor_onbo_status_2aeb77_idx',
            old_name='vendor_sub_status_idx',
        ),
        migrations.RenameIndex(
            model_name='vendoronboardingsubmission',
            new_name='vendor_onbo_normali_ca8b5e_idx',
            old_name='vendor_sub_email_idx',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='scope_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='core.scopenode'),
        ),
    ]
