# Generated by Django 4.2.29 on 2026-04-18 10:12

import apps.vendors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_rename_vendors_org_opstatus_idx_vendors_org_id_0616db_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorattachment',
            name='file',
            field=models.FileField(blank=True, upload_to=apps.vendors.models._vendor_attachment_upload_path),
        ),
        migrations.AlterField(
            model_name='vendorattachment',
            name='file_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
