# Generated by Django 4.2.29 on 2026-04-18 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0004_vendorattachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorActivationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, help_text='User ID (uid) used in the activation URL', max_length=64)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vendor Activation Token',
                'verbose_name_plural': 'Vendor Activation Tokens',
                'db_table': 'vendor_activation_tokens',
                'indexes': [models.Index(fields=['uid', 'token'], name='vendor_acti_uid_a251e3_idx'), models.Index(fields=['uid', 'used_at'], name='vendor_acti_uid_665f5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserVendorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_assignments', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='vendors.vendor')),
            ],
            options={
                'db_table': 'user_vendor_assignments',
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_vendor_user_id_d2e17c_idx'), models.Index(fields=['vendor', 'is_active'], name='user_vendor_vendor__46e4cf_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='uservendorassignment',
            constraint=models.UniqueConstraint(fields=('user', 'vendor'), name='unique_user_vendor_assignment'),
        ),
    ]
