# Generated by Django 4.2.29 on 2026-04-18 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0005_vendor_activation_and_user_binding'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='portal_activation_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the last activation email was sent', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='portal_email',
            field=models.EmailField(blank=True, help_text='Cached portal user email for display', max_length=254),
        ),
        migrations.AddField(
            model_name='vendor',
            name='portal_user_id',
            field=models.CharField(blank=True, help_text='User ID of the portal user (cached for display, not FK)', max_length=64),
        ),
        migrations.AddField(
            model_name='vendoractivationtoken',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='When the activation email was last sent', null=True),
        ),
        migrations.AddField(
            model_name='vendoractivationtoken',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_vendor_activation_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendoractivationtoken',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Denormalized vendor reference for display', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activation_tokens', to='vendors.vendor'),
        ),
    ]
