# Generated by Django 4.2.29 on 2026-04-22 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('workflow', '0008_stepkind_single_allocation'),
        ('vendors', '0006_vendor_portal_tracking_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSubmissionRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable internal key, unique within org. Never shown to vendor.', max_length=100)),
                ('label', models.CharField(help_text="What the vendor sees, e.g. 'Tarun'.", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_submission_routes', to='core.organization')),
                ('workflow_template', models.ForeignKey(help_text='Published version is resolved at submit time.', on_delete=django.db.models.deletion.PROTECT, related_name='vendor_submission_routes', to='workflow.workflowtemplate')),
            ],
            options={
                'db_table': 'vendor_submission_routes',
                'ordering': ['display_order', 'label'],
                'indexes': [models.Index(fields=['org', 'is_active'], name='vendor_subm_org_id_ce6ade_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='vendorsubmissionroute',
            constraint=models.UniqueConstraint(fields=('org', 'code'), name='unique_route_code_per_org'),
        ),
    ]
