# Generated by Django 4.2.29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0007_vendor_submission_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="contact_persons_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="declaration_accepted",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="head_office_address_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_address_line3",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_authorized_signatory_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_bank_account_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_bank_branch_address_line1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_bank_branch_address_line2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_bank_branch_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_bank_branch_country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_bank_branch_pincode",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_bank_branch_state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_bank_fax",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_bank_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_beneficiary_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_fax",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_head_office_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_micr_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_msme_enterprise_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_msme_registered",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_msme_registration_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_neft_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_preferred_payment_mode",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_region",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="normalized_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vendoronboardingsubmission",
            name="tax_registration_details_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
