# Generated by Django 4.2.29 on 2026-04-25 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0008_vendor_onboarding_extended_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='profile_change_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='profile_hold_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vendor',
            name='profile_hold_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VendorProfileRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('sent_to_finance', 'Sent to Finance'), ('finance_approved', 'Finance Approved'), ('finance_rejected', 'Finance Rejected'), ('reopened', 'Reopened'), ('marketing_pending', 'Marketing Pending'), ('marketing_approved', 'Marketing Approved'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('proposed_snapshot_json', models.JSONField(default=dict)),
                ('changed_fields_json', models.JSONField(default=list)),
                ('source_revision_snapshot_json', models.JSONField(default=dict)),
                ('finance_sent_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendor_profile_revisions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_vendor_profile_revisions', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_revisions', to='vendors.vendor')),
            ],
            options={
                'db_table': 'vendor_profile_revisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='active_profile_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holding_vendor', to='vendors.vendorprofilerevision'),
        ),
        migrations.AddIndex(
            model_name='vendorprofilerevision',
            index=models.Index(fields=['vendor', 'status'], name='vendor_prof_vendor__0b6046_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendorprofilerevision',
            constraint=models.UniqueConstraint(fields=('vendor', 'revision_number'), name='unique_revision_number_per_vendor'),
        ),
    ]
