# Generated by Django 4.2.29 on 2026-04-25 07:28

from django.db import migrations, models


def _backfill_vendor_profile_fields(apps, schema_editor):
    """
    Backfill the new approved profile fields on Vendor from the
    corresponding VendorOnboardingSubmission for all vendors that have one.

    This makes Vendor the authoritative source of truth for the approved live
    vendor profile. VendorOnboardingSubmission retains its historical onboarding
    data but is no longer the live profile store.
    """
    Vendor = apps.get_model("vendors", "Vendor")
    VendorOnboardingSubmission = apps.get_model("vendors", "VendorOnboardingSubmission")

    # Map Vendor field name → VendorOnboardingSubmission normalized field name
    FIELD_MAP = {
        "title": "normalized_title",
        "vendor_type": "normalized_vendor_type",
        "fax": "normalized_fax",
        "region": "normalized_region",
        "head_office_no": "normalized_head_office_no",
        "gst_registered": "normalized_gst_registered",
        "gstin": "normalized_gstin",
        "pan": "normalized_pan",
        "address_line1": "normalized_address_line1",
        "address_line2": "normalized_address_line2",
        "address_line3": "normalized_address_line3",
        "city": "normalized_city",
        "state": "normalized_state",
        "country": "normalized_country",
        "pincode": "normalized_pincode",
        "preferred_payment_mode": "normalized_preferred_payment_mode",
        "beneficiary_name": "normalized_beneficiary_name",
        "bank_name": "normalized_bank_name",
        "account_number": "normalized_account_number",
        "bank_account_type": "normalized_bank_account_type",
        "ifsc": "normalized_ifsc",
        "micr_code": "normalized_micr_code",
        "neft_code": "normalized_neft_code",
        "bank_branch_address_line1": "normalized_bank_branch_address_line1",
        "bank_branch_address_line2": "normalized_bank_branch_address_line2",
        "bank_branch_city": "normalized_bank_branch_city",
        "bank_branch_state": "normalized_bank_branch_state",
        "bank_branch_country": "normalized_bank_branch_country",
        "bank_branch_pincode": "normalized_bank_branch_pincode",
        "bank_phone": "normalized_bank_phone",
        "bank_fax": "normalized_bank_fax",
        "authorized_signatory_name": "normalized_authorized_signatory_name",
        "msme_registered": "normalized_msme_registered",
        "msme_registration_number": "normalized_msme_registration_number",
        "msme_enterprise_type": "normalized_msme_enterprise_type",
        "declaration_accepted": "declaration_accepted",
        # JSON blocks
        "contact_persons_json": "contact_persons_json",
        "head_office_address_json": "head_office_address_json",
        "tax_registration_details_json": "tax_registration_details_json",
    }

    updated = 0
    for vendor in Vendor.objects.select_related("onboarding_submission").filter(
        onboarding_submission__isnull=False
    ):
        sub = vendor.onboarding_submission
        if sub is None:
            continue
        update_fields = []
        for vendor_field, sub_field in FIELD_MAP.items():
            new_val = getattr(sub, sub_field, None)
            current_val = getattr(vendor, vendor_field, None)
            if new_val != current_val:
                setattr(vendor, vendor_field, new_val)
                update_fields.append(vendor_field)
        if update_fields:
            # Also sync the already-present Vendor-level fields from submission
            if sub.normalized_vendor_name and vendor.vendor_name != sub.normalized_vendor_name:
                vendor.vendor_name = sub.normalized_vendor_name
                update_fields.append("vendor_name")
            if sub.normalized_email and vendor.email != sub.normalized_email:
                vendor.email = sub.normalized_email
                update_fields.append("email")
            if sub.normalized_phone and vendor.phone != sub.normalized_phone:
                vendor.phone = sub.normalized_phone
                update_fields.append("phone")
            update_fields.append("updated_at")
            vendor.save(update_fields=update_fields)
            updated += 1

    # vendors without onboarding_submission: only sync name/email/phone if blank
    for vendor in Vendor.objects.filter(onboarding_submission__isnull=True):
        update_fields = []
        for field in ("vendor_name", "email", "phone"):
            if not getattr(vendor, field, None):
                update_fields.append(field)
        if update_fields:
            update_fields.append("updated_at")
            vendor.save(update_fields=update_fields)
            updated += 1

    print(f"[backfill] Updated {updated} vendor records.")


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_vendor_profile_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='address_line3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='authorized_signatory_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_account_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_branch_address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_branch_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_branch_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_branch_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_branch_pincode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_branch_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_fax',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_persons_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vendor',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='declaration_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='fax',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gst_registered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gstin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='head_office_address_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vendor',
            name='head_office_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='ifsc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='micr_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='msme_enterprise_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='msme_registered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='msme_registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='neft_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pan',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pincode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='preferred_payment_mode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tax_registration_details_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vendor',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorprofilerevision',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('finance_approved', 'Finance Approved'), ('finance_rejected', 'Finance Rejected'), ('reopened', 'Reopened'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
        migrations.RunPython(_backfill_vendor_profile_fields, reverse_code=migrations.RunPython.noop),
    ]