# Generated by Django 5.0.6 on 2026-06-04 09:31

import apps.vendors.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_vrf_bank_detail_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorTrainingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='How to Submit an Invoice', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_file', models.FileField(upload_to=apps.vendors.models._vendor_training_video_upload_path)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendor_training_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vendor_training_videos',
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['is_active', '-updated_at'], name='vendor_trai_is_acti_f3420c_idx')],
            },
        ),
    ]
