# Generated by Django 5.0.6 on 2026-06-20 06:03

import apps.document_ingestion.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('invoices', '0012_vendorinvoicesubmission_original_normalized_data'),
        ('vendors', '0013_vendor_training_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDocumentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('connector_type', models.CharField(choices=[('local', 'Local Folder'), ('sftp', 'SFTP'), ('ftp', 'FTP'), ('sharepoint', 'SharePoint')], max_length=30)),
                ('config_key', models.CharField(help_text='Environment-variable prefix used by the connector, e.g. HORIZON_FINANCE_SFTP.', max_length=100)),
                ('base_path', models.CharField(blank=True, max_length=1000)),
                ('public_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sources', to='core.organization')),
            ],
            options={
                'db_table': 'external_document_sources',
            },
        ),
        migrations.CreateModel(
            name='ExternalDocumentImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_identifier', models.CharField(blank=True, max_length=1000)),
                ('remote_path', models.CharField(blank=True, max_length=2000)),
                ('original_filename', models.CharField(max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('source_file', models.FileField(upload_to=apps.document_ingestion.models.external_document_upload_path)),
                ('document_type', models.CharField(choices=[('unknown', 'Unknown'), ('invoice', 'Invoice'), ('payment_advice', 'Payment Advice')], default='unknown', max_length=30)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('downloaded', 'Downloaded'), ('extracted', 'Extracted'), ('matched', 'Matched'), ('review_required', 'Review Required'), ('applied', 'Applied'), ('duplicate', 'Duplicate'), ('quarantined', 'Quarantined'), ('failed', 'Failed')], db_index=True, default='discovered', max_length=30)),
                ('raw_extracted_data', models.JSONField(blank=True, default=dict)),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('processing_attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_external_document_imports', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_documents', to='document_ingestion.externaldocumentimport')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_document_imports', to='core.organization')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='document_ingestion.externaldocumentsource')),
            ],
            options={
                'db_table': 'external_document_imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalDocumentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_document_events', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='document_ingestion.externaldocumentimport')),
            ],
            options={
                'db_table': 'external_document_events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['document', 'created_at'], name='external_do_documen_c0d37f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExternalDocumentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_index', models.PositiveIntegerField(default=1)),
                ('document_type', models.CharField(choices=[('unknown', 'Unknown'), ('invoice', 'Invoice'), ('payment_advice', 'Payment Advice')], default='unknown', max_length=30)),
                ('match_status', models.CharField(choices=[('not_attempted', 'Not Attempted'), ('matched', 'Matched'), ('ambiguous', 'Ambiguous'), ('unmatched', 'Unmatched'), ('conflict', 'Conflict')], db_index=True, default='not_attempted', max_length=30)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_document_records', to='invoices.invoicepayment')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='document_ingestion.externaldocumentimport')),
                ('matched_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_external_document_records', to='invoices.invoice')),
                ('matched_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_external_document_records', to='vendors.vendor')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_external_document_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'external_document_records',
                'ordering': ['record_index'],
                'indexes': [models.Index(fields=['document_type', 'match_status'], name='external_do_documen_3e536a_idx'), models.Index(fields=['matched_invoice'], name='external_do_matched_01850d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='externaldocumentrecord',
            constraint=models.UniqueConstraint(fields=('document', 'record_index'), name='unique_record_index_per_document'),
        ),
        migrations.AddIndex(
            model_name='externaldocumentsource',
            index=models.Index(fields=['org', 'is_active'], name='external_do_org_id_dd4e63_idx'),
        ),
        migrations.AddConstraint(
            model_name='externaldocumentsource',
            constraint=models.UniqueConstraint(fields=('org', 'name'), name='unique_document_source_name_per_org'),
        ),
        migrations.AddIndex(
            model_name='externaldocumentimport',
            index=models.Index(fields=['org', 'status'], name='external_do_org_id_b6050e_idx'),
        ),
        migrations.AddIndex(
            model_name='externaldocumentimport',
            index=models.Index(fields=['document_type', 'status'], name='external_do_documen_cb6269_idx'),
        ),
        migrations.AddConstraint(
            model_name='externaldocumentimport',
            constraint=models.UniqueConstraint(condition=models.Q(('remote_identifier', ''), _negated=True), fields=('source', 'remote_identifier'), name='unique_remote_document_per_source'),
        ),
    ]
