# Generated by Django 5.0.6 on 2026-04-15 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('reassign', 'Reassign'), ('start_workflow', 'Start Workflow'), ('manage_module', 'Manage Module')], max_length=50)),
                ('resource', models.CharField(choices=[('invoice', 'Invoice'), ('campaign', 'Campaign'), ('vendor', 'Vendor'), ('budget', 'Budget'), ('workflow', 'Workflow'), ('module', 'Module'), ('user', 'User'), ('role', 'Role')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Unique within org', max_length=100)),
                ('node_type_scope', models.CharField(blank=True, help_text='Which node_type this role is valid for. Empty = all types.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'role_permissions',
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_role_assignments',
            },
        ),
        migrations.CreateModel(
            name='UserScopeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('primary', 'Primary'), ('additional', 'Additional'), ('delegated', 'Delegated')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_scope_assignments',
            },
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(fields=('action', 'resource'), name='unique_permission'),
        ),
        migrations.AddField(
            model_name='role',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.organization'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='access.permission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='access.role'),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='access.role'),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='scope_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_assignments', to='core.scopenode'),
        ),
    ]
