# Generated by Django 5.0.6 on 2026-04-15 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userroleassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userscopeassignment',
            name='scope_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scope_assignments', to='core.scopenode'),
        ),
        migrations.AddField(
            model_name='userscopeassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('org', 'code'), name='unique_role_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission'),
        ),
        migrations.AddIndex(
            model_name='userroleassignment',
            index=models.Index(fields=['user', 'scope_node'], name='user_role_a_user_id_730da5_idx'),
        ),
        migrations.AddIndex(
            model_name='userroleassignment',
            index=models.Index(fields=['role', 'scope_node'], name='user_role_a_role_id_6f9279_idx'),
        ),
        migrations.AddConstraint(
            model_name='userroleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'scope_node'), name='unique_user_role_assignment'),
        ),
        migrations.AddConstraint(
            model_name='userscopeassignment',
            constraint=models.UniqueConstraint(fields=('user', 'scope_node', 'assignment_type'), name='unique_user_scope_assignment'),
        ),
    ]
