# Generated by Django 5.0.6 on 2026-06-27 07:53

from django.db import migrations, models


def grant_historical_post_permission(apps, schema_editor):
    Permission = apps.get_model("access", "Permission")
    Role = apps.get_model("access", "Role")
    RolePermission = apps.get_model("access", "RolePermission")

    permission, _ = Permission.objects.get_or_create(
        action="historical_post",
        resource="invoice",
        defaults={"description": "Post or reverse historical invoices directly to the budget ledger"},
    )
    for role in Role.objects.filter(code__in=("tenant_admin", "org_admin")):
        RolePermission.objects.get_or_create(role=role, permission=permission)


def revoke_historical_post_permission(apps, schema_editor):
    Permission = apps.get_model("access", "Permission")
    permission = Permission.objects.filter(
        action="historical_post",
        resource="invoice",
    ).first()
    if permission:
        permission.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('reassign', 'Reassign'), ('start_workflow', 'Start Workflow'), ('manage_module', 'Manage Module'), ('historical_post', 'Post Historical Record')], max_length=50),
        ),
        migrations.RunPython(
            grant_historical_post_permission,
            revoke_historical_post_permission,
        ),
    ]
